version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: teachm_user
      WORDPRESS_DB_PASSWORD: teachm_pass
      WORDPRESS_DB_NAME: teachm_db
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: teachm_db
      MYSQL_USER: teachm_user
      MYSQL_PASSWORD: teachm_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: